# Generated by Django 6.0 on 2026-01-27 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Curva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("fecha", models.DateField()),
                ("plazos", models.JSONField()),
                ("tipos", models.JSONField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_contrato", models.CharField(max_length=50)),
                ("producto", models.CharField(max_length=100)),
                ("activo_pasivo", models.CharField(max_length=10)),
                ("nominal", models.FloatField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_vencimiento", models.DateField()),
                ("tipo_interes", models.CharField(max_length=10)),
                ("tipo_amortizacion", models.CharField(max_length=10)),
                ("cupon_spread", models.FloatField()),
                ("curva_asociada", models.CharField(max_length=100)),
                ("frecuencia_cupon", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "banco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos",
                        to="irrbb_app.banco",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultadoBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_calculo", models.DateTimeField(auto_now_add=True)),
                ("eve_base", models.FloatField(default=0)),
                ("eve_parallel_up", models.FloatField(default=0)),
                ("eve_parallel_down", models.FloatField(default=0)),
                ("eve_steepener", models.FloatField(default=0)),
                ("eve_flattener", models.FloatField(default=0)),
                ("eve_short_up", models.FloatField(default=0)),
                ("eve_short_down", models.FloatField(default=0)),
                ("nii_base", models.FloatField(default=0)),
                ("nii_parallel_up", models.FloatField(default=0)),
                ("nii_parallel_down", models.FloatField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "banco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="irrbb_app.banco",
                    ),
                ),
            ],
        ),
    ]
