# Generated by Django 6.0 on 2026-01-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="birth_date",
        ),
    ]
